FROM node:20-buster

WORKDIR /app

COPY package.json yarn.lock ./
COPY lerna.json ./
COPY packages/client/package.json ./packages/client/package.json
COPY packages/server/package.json ./packages/server/package.json

RUN yarn install --frozen-lockfile --ignore-scripts

CMD ["yarn", "dev:server"]