ARG NODE_VERSION=20
ARG SERVER_PORT
FROM node:${NODE_VERSION}-buster AS base
WORKDIR /app

COPY package.json yarn.lock lerna.json ./
COPY packages/client/package.json ./packages/client/
COPY packages/server/package.json ./packages/server/
RUN yarn install --frozen-lockfile

FROM base AS dev
COPY . .
EXPOSE ${SERVER_PORT}

CMD ["yarn", "--cwd", "packages/server", "dev"]
