services:
  client:
    container_name: prakticum-client-dev
    build:
      context: .
      dockerfile: Dockerfile.client.dev
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./packages/client:/app/packages/client
      - ./package.json:/app/package.json
      - ./lerna.json:/app/lerna.json
    depends_on:
      - server

  server:
    container_name: prakticum-server-dev
    build:
      context: .
      dockerfile: Dockerfile.server.dev
      args:
        SERVER_PORT: ${SERVER_PORT}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./packages/server:/app/packages/server
      - ./package.json:/app/package.json
      - ./lerna.json:/app/lerna.json
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
