services:
  server:
    container_name: prakticum-app
    image: ghcr.io/sh1nbatsu/cuddly-invention/server:99b9a6f85eb38bcac2583685ad93a4b972da7d30
    restart: always
    ports:
      - '3001:3001'
    environment:
      SERVER_PORT: 3001
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: titlepostgres
      POSTGRES_DB: postgres
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: titlepostgres
      POSTGRES_USER: postgresuser
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: