# ИСПРАВЛЕННЫЙ docker-compose.yml

services:
  # Наш единственный сервис приложения
  server:
    container_name: prakticum-app
    # Собираем из нового, единого Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file: .env
    # Передаем переменные, включая SERVER_PORT
    environment:
      SERVER_PORT: ${SERVER_PORT}
      # Другие переменные из .env тоже будут доступны
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_CONTAINER_PORT}'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: