name: Deploy to virtual machine

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  rebuild-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy

    env:
      DOCKER_HOST: ssh://${{ secrets.VM_USERNAME }}@${{ secrets.PRODUCTION_HOST }}

    steps:
      - name: Connect to docker
        run: | 
          export DOCKER_HOST=${DOCKER_HOST}
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_PRIVATE_SSH_KEY }}
      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
      - name: Check connection to Docker
        run: docker ps
      # - name: Rebuild and deploy
        # run: |
        #   docker compose pull
        #   docker compose up -d --build
        #   exit