name: Deploy to virtual machine

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Log secret in console
        run: echo "Connecting to host ${{ deploy.PRODUCTION_PRIVATE_SSH_KEY }}"
