name: Deploy to virtual machine

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  rebuild-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy

    env:
      DOCKER_HOST: ssh://${{ secrets.VM_USERNAME }}@${{ secrets.PRODUCTION_HOST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Connect to docker
        run: |
          export DOCKER_HOST=${DOCKER_HOST}
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_PRIVATE_SSH_KEY }}
      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
      - name: Rebuild and deploy
        env:
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_CONTAINER_PORT: ${{ secrets.POSTGRES_CONTAINER_PORT }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          cd ${{ github.workspace }}
          ls
          docker compose -p dino-app pull
          docker compose -p dino-app up -d --force-recreate
