name: Deploy to virtual machine

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  rebuild-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy # Отлично, что используете окружения!

    # Устанавливаем DOCKER_HOST для всех шагов в этом задании
    env:
      DOCKER_HOST: ssh://${{ secrets.VM_USERNAME }}@${{ secrets.PRODUCTION_HOST }}

    steps:
      # 1. Используем экшен для настройки SSH-агента.
      # Он сам запустит агент и добавит ваш ключ.
      - name: Connect to docker
        uses: actions/checkout@v3
        run: | 
          export DOCKER_HOST=${DOCKER_HOST}

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_PRIVATE_SSH_KEY }}

      # 2. (Опционально, но рекомендуется) Добавляем хост в known_hosts
      # Это предотвратит интерактивный запрос "Are you sure you want to continue connecting (yes/no)?"
      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts

      # 3. Теперь Docker может подключиться через SSH, используя ключ из агента
      - name: Check connection to Docker
        run: docker ps