name: Deploy to virtual machine

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  rebuild-and-deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Log secret in console
        run: echo "Connecting to host ${{ secrets.PRODUCTION_PRIVATE_SSH_KEY }}"
      - name: Download Openssh and Git
        run: sudo apt-get --no-cache install openssh-client git openssh
      - name: Initialize SSH agent
        run: eval $(ssh-agent -s)
      - name: Add private SSH key
        run: echo "${{ secrets.PRODUCTION_PRIVATE_SSH_KEY }}" >> /tmp/id_rsa
      - name: Set permissions for SSH key
        run: |
          - chmod 600 /tmp/id_rsa
          - ssh-add /tmp/id_rsa || { echo "Failed to add SSH key"; cat /tmp/id_rsa; exit 1; }
          - mkdir -p ~/.ssh
          - chmod 700 ~/.ssh
          - ssh-keyscan ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
          - chmod 644 ~/.ssh/known_hosts
      - name: Connect to Docker
        run: export DOCKER_HOST=ssh://${{ secrets.VM_USERNAME }}@${{ secrets.PRODUCTION_HOST }}
      - name: Check connection to docker
        run: docker ps

# 1 Скачать open ssh и гит
# 2 evalssh
# 3 /tmp/id_rsa в эту папку положить приватный ключ
# mkdir -p ~/.ssh
